version: "3.8"
services:
    base:
        image: unterwegs:base
        build: ./dockers/base
    redis:
        image: redis:7.0.5-bullseye
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
    web:
        build: ./dockers/web
        ports:
            - 5000:5000
        volumes:
            - ./unterwegs:/web/unterwegs
            - ./public:/public
            - ./data/uploads:/uploads
        depends_on:
            - redis
        links:
            - redis:redis
            - typesense:typesense
            - master:master
            - volume:volume
            - filer:filer
    worker:
        build: ./dockers/worker
        volumes:
            - ./data/worker:/data
            - ./data/uploads:/uploads
            - ./unterwegs:/worker/unterwegs
        depends_on:
            - redis
        links:
            - redis:redis
            - typesense:typesense
            - master:master
            - volume:volume
            - filer:filer
    typesense:
        image: typesense/typesense:0.23.1
        ports:
            - 8108:8108
        volumes:
            - ./data/index:/index
        environment:
            TYPESENSE_API_KEY: MUzQD3ncGDBihx6YGTBeBJ4Q
            TYPESENSE_DATA_DIR: "/index"
    master:
        image: chrislusf/seaweedfs:latest
        ports:
            - 9333:9333
            - 19333:19333
        command: "master -ip=master"
        volumes:
            - ./data/master:/data
    volume:
        image: chrislusf/seaweedfs:latest
        ports:
            - 8080:8080
            - 18080:18080
        command: 'volume -mserver="master:9333" -port=8080'
        depends_on:
            - master
        volumes:
            - ./data/volume:/data
    filer:
        image: chrislusf/seaweedfs:latest
        ports:
            - 8888:8888
            - 18888:18888
        command: 'filer -master="master:9333"'
        tty: true
        stdin_open: true
        depends_on:
            - master
            - volume
        volumes:
            - ./data/filer:/data
    tile38:
        image: tile38/tile38:latest
        ports:
            - 9851:9851
        volumes:
            - ./data/tile38:/data
